/// <reference types="cypress" />

describe('Testes de fluxo feliz', () => {
  beforeEach(() =>{
    cy.visit('https://sistema-de-comanda.surge.sh/')
    cy.viewport(375,667)
    cy.get('body').should('contain','BEM-VINDO')
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/login')
  })
  it('Cadastro com sucesso', () => {
    cy.get(':nth-child(3) > p > a').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/registerClient')
    cy.get('[name="nome"]').type('victor')
    cy.get('[name="sobrenome"]').type('zamora')
    cy.get('#mui-component-select-sexo').click()
    cy.get('.MuiList-root > [tabindex="0"]').click()
    cy.get('[name="Data de Nascimento"]').type('2002-01-23')
    cy.get('[name="cpf"]').type('12345698735')
    cy.get('[name="tel"]').type('11999991111')
    cy.get('[name="email"]').type('victor.semerano@email.com')
    cy.get('[name="password"]').type('Aaaa@123')
    cy.get('.MuiButton-root').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/login')
  })

  it('Login com sucesso', () => {
    cy.get('[name="email"]').type('victor.semerano@email.com ')
    cy.get('[name="password"]').type('Aaaa@123')
    cy.get('.MuiButton-root').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/home')
  })
  it('Redefinição de senha com sucesso',()=>{
    cy.get('.css-0 > a').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/forgotpassword')
    cy.get('.MuiTypography-root').should('contain','Redefinir a senha')
    cy.get('.MuiButton-root').click()
    cy.get('.chakra-text').should('contain','Por favor, verifique seu email')
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/verifyemail')
    })
  
  it('Acessar estabelecimento',()=>{
    cy.get('[name="email"]').type('victor.semerano@email.com ')
    cy.get('[name="password"]').type('Aaaa@123')
    cy.get('.MuiButton-root').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/home')
    cy.get(':nth-child(3) > img').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/restaurant/1')
  })

  it('Adicionar item ao carrinho',()=>{
    cy.visit('https://sistema-de-comanda.surge.sh/restaurant/1')
    cy.get('#root > :nth-child(1) > :nth-child(1) > :nth-child(1)').should('contain','Habibs')
    .should('contain','Árabe')
    .should('contain','Rua das Margaridas, 110')
    cy.get('html').should('contain','Esfiha de carne')
    cy.get('button').first().click()
    cy.get('#demo-simple-select').type('1')
    cy.get('.MuiList-root > [tabindex="0"]').click()
    cy.get('.MuiButton-root').click()
  })

  it('Fluxo cliente',()=>{
    cy.get('[name="email"]').type('victor.semerano@email.com ')
    cy.get('[name="password"]').type('Aaaa@123')
    cy.get('.MuiButton-root').click()
    cy.get('.hamb-line').click()
    cy.get(':nth-child(2) > .nav-item').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/cart')
    cy.get('html').should('contain','Esfiha de carne')
    .should('contain','Pix')
    .should('contain','Confirmar')
    .should('contain','Dinheiro')
    .should('contain','Cartão de Crédito')
    cy.get('[id="money"]').click()
    cy.get('button').last().click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/cart?paymentMethod=money')
    cy.get('.hamb-line').click()
    cy.get(':nth-child(3) > .nav-item').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/profile')
    cy.get('.sc-cxabCf').should('contain','Usuário')
    cy.get('.hamb-line').click()
    cy.get(':nth-child(1) > .nav-item').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/home')
  })

  it('Fluxo atendente',()=>{
    cy.get('[name="email"]').type('victor.semerano@email.com ')
    cy.get('[name="password"]').type('Aaaa@123')
    cy.get('.MuiButton-root').click()
    cy.get('.hamb-line').click()
    cy.get(':nth-child(3) > .nav-item').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/profile')
    cy.get('.hamb-line').click()
    cy.get(':nth-child(4) > .nav-item').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/homeAttendant')
    cy.get(':nth-child(3) > img').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/order/0')
    cy.get('html').should('contain','Esfiha de carne')
    cy.get('html').should('contain','Cancelar')
    cy.get('.hamb-line').click()
    cy.get(':nth-child(2) > .nav-item').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/tables')
    cy.get('.header > p').should('contain','Mesas')
  })

  it('Fluxo logista',()=>{
    cy.get('[name="email"]').type('victor.semerano@email.com ')
    cy.get('[name="password"]').type('Aaaa@123')
    cy.get('.MuiButton-root').click()
    cy.get('.hamb-line').click()
    cy.get(':nth-child(3) > .nav-item').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/profile')
    cy.get('.hamb-line').click()
    cy.get(':nth-child(6) > .nav-item').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/homeRestaurant')
    cy.get(':nth-child(3) > img').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/attendant/0')
    cy.get('html').should('contain','José')
    .should('contain','Masculino')
    .should('contain','27 anos')
    .should('contain','444.444.444-44')
    .should('contain','Status atual: Ocupado')
    .should('contain','Avaliação geral: 9')
    cy.get('.hamb-line').click()
    cy.get(':nth-child(2) > .nav-item').click()
    cy.url().should('eq','https://sistema-de-comanda.surge.sh/product')
    cy.get(':nth-child(3) > img').click()
    cy.get('html').should('contain','Esfiha de carne')
    .should('contain','2.88')
    .should('contain','Restaurante: Habibs')
    .should('contain','Carne temperada com limão, tomate, tahine, cebola e tempero especial')
    .should('contain','Quantidade em estoque: 5000')
  })
})